# All in Marrakech – tours and day trips (EN + FR).
# Prices are "from" prices in EUR for a private vehicle with driver (1–4 travellers).
# tiers = per-vehicle price table (reference price + 20 EUR), one entry per vehicle size; programs without it use site.TIER_ADD steps.
U = "https://allinmarrakech.com/wp-content/uploads/2026/10/"

IMG = {
    "chefchaouen": U + "A_view_of_one_of_the_many_blue-painted_streets_in_Chefchaouen_Morocco.jpg",
    "aitbenhaddou": U + "Kasbah_-_Ait_Ben_Haddou_-_Morocco_-_panoramio.jpg",
    "merzouga": U + "Erg_Chebbi_Dunes_Camel_LL.jpg",
    "ouzoud": U + "Ouzoud_Waterfall.jpg",
    "jemaa": U + "Jemaa_el-Fnaa_Marrakech_at_sunset.jpg",
    "todra": U + "Togra_Gorge.jpg",
    "majorelle": U + "Marrakech_Majorelle_Garden_2011.jpg",
    "agafay": U + "Agafay_Desert_Morocco_20250125_1802_7284.jpg",
    "ourika": U + "Ourika_Valley.jpg",
    "imlil": U + "Imlil_village_High_Atlas_Mountains.jpg",
    "casablanca": U + "Sunrise_in_Casablanca_with_Hassan_II_Mosque.jpg",
    "rabat": U + "Hassan_Tower.jpg",
    "dades": U + "The_zigzagging_road_of_the_Dades_Gorge_in_southern_Morocco.jpg",
    "oukaimeden": U + "Oukaimden_village.jpg",
    "binelouidane": U + "Bin_el_Ouidane_lake_From_above-Morocco.jpg",
    "zagora": U + "Vallee_du_draa.jpg",
    "koutoubia": U + "Koutoubia_MosqueMarrakechMorocco.jpg",
    "fes": U + "Medina_of_Fes_Marocco.jpg",
}

CREDITS = [
    ("Chefchaouen", "Mark Fischer", "CC BY 3.0"),
    ("Aït Ben Haddou", "Panoramio", "CC BY-SA 3.0"),
    ("Erg Chebbi", "Lionel Leo", "GFDL"),
    ("Ouzoud", "Antony Stanley", "CC BY 2.0"),
    ("Majorelle", "Bjørn Christian Tørrissen", "CC BY-SA 3.0"),
    ("Agafay", "Jakub Hałun", "CC BY 4.0"),
    ("Ourika", "Bryce Edwards", "CC BY 2.0"),
    ("Imlil", "Mounir Neddi", "CC BY-SA 4.0"),
    ("Casablanca", "SpreeTom", "CC BY-SA 4.0"),
    ("Rabat", "Bernard Gagnon", "CC BY-SA 3.0"),
    ("Dadès", "Nawfal Kharbach", "CC BY-SA 4.0"),
    ("Bin El Ouidane", "Kasmii", "CC BY-SA 4.0"),
    ("Draa Valley", "Theoliane", "CC BY-SA"),
    ("Koutoubia", "Marcin Sochacki", "CC BY-SA"),
]

P = []


def add(**k):
    P.append(k)


# ---------------------------------------------------------------- CIRCUITS
add(key="chefchaouen", kind="circuit", img="chefchaouen", price=720, tiers=[720, 770, 820, 920, 1520],
    en=dict(slug="marrakech-chefchaouen-tour", title="Marrakech to Chefchaouen: the Blue City Tour",
            dur="5 days / 4 nights",
            short="Casablanca, Rabat, two nights in the blue medina of Chefchaouen and Fes on the way back.",
            intro="A private road trip from Marrakech to the north, with time to really enjoy Chefchaouen instead of rushing through it. You stop at the great sights of the Atlantic coast on the way up and come back through Fes and the cedar forests of the Middle Atlas.",
            hl=["Hassan II Mosque in Casablanca", "Hassan Tower and Kasbah of the Udayas in Rabat",
                "Two nights in Chefchaouen, sunset from the Spanish Mosque", "Afternoon in the old medina of Fes",
                "Ifrane and the Barbary macaques of the cedar forest"],
            days=[("Marrakech – Casablanca – Rabat", "Morning pick-up at your riad or hotel. Motorway to Casablanca for a stop at the Hassan II Mosque on the ocean front, then on to Rabat. Late afternoon walk around the Hassan Tower and the Mausoleum of Mohammed V. Night in Rabat."),
                  ("Rabat – Chefchaouen", "Short morning visit of the Kasbah of the Udayas and its Andalusian garden, then the road climbs into the Rif foothills. Arrival in Chefchaouen in the afternoon and first steps in the blue alleys. Night in Chefchaouen."),
                  ("Chefchaouen at your own pace", "A free day in the Blue City: the Outa el Hammam square, the kasbah, the Ras El Maa spring where locals do their washing, and a short walk up to the Spanish Mosque for sunset over the valley. Night in Chefchaouen."),
                  ("Chefchaouen – Fes", "Drive south through olive groves to Fes (about 4 hours). Afternoon in Fes el Bali: Bab Boujloud, the Bou Inania madrasa and a terrace view over the Chouara tanneries. Night in Fes."),
                  ("Fes – Ifrane – Marrakech", "Through the Middle Atlas to Ifrane, the 'Switzerland of Morocco', and the Azrou cedar forest where wild macaques live. Lunch stop on the way, then down through Beni Mellal to Marrakech in the evening.")]),
    fr=dict(slug="circuit-marrakech-chefchaouen", title="Circuit Marrakech – Chefchaouen, la ville bleue",
            dur="5 jours / 4 nuits",
            short="Casablanca, Rabat, deux nuits dans la médina bleue de Chefchaouen et Fès au retour.",
            intro="Un road trip privé de Marrakech vers le nord, avec le temps de vraiment profiter de Chefchaouen au lieu de la traverser en courant. À l'aller, les grands sites de la côte atlantique ; au retour, Fès et les forêts de cèdres du Moyen Atlas.",
            hl=["La mosquée Hassan II à Casablanca", "La tour Hassan et la kasbah des Oudayas à Rabat",
                "Deux nuits à Chefchaouen, coucher de soleil depuis la mosquée espagnole", "Un après-midi dans la vieille médina de Fès",
                "Ifrane et les singes magots de la forêt de cèdres"],
            days=[("Marrakech – Casablanca – Rabat", "Prise en charge le matin à votre riad ou hôtel. Autoroute vers Casablanca et arrêt à la mosquée Hassan II face à l'océan, puis route vers Rabat. En fin d'après-midi, balade à la tour Hassan et au mausolée Mohammed V. Nuit à Rabat."),
                  ("Rabat – Chefchaouen", "Courte visite de la kasbah des Oudayas et de son jardin andalou, puis la route monte vers les contreforts du Rif. Arrivée à Chefchaouen l'après-midi et premiers pas dans les ruelles bleues. Nuit à Chefchaouen."),
                  ("Chefchaouen à votre rythme", "Journée libre dans la ville bleue : la place Outa el Hammam, la kasbah, la source de Ras El Maa où les habitants lavent leur linge, et une petite montée jusqu'à la mosquée espagnole pour le coucher de soleil. Nuit à Chefchaouen."),
                  ("Chefchaouen – Fès", "Route vers le sud à travers les oliveraies jusqu'à Fès (environ 4 heures). Après-midi à Fès el Bali : Bab Boujloud, la médersa Bou Inania et la vue sur les tanneries Chouara depuis une terrasse. Nuit à Fès."),
                  ("Fès – Ifrane – Marrakech", "Traversée du Moyen Atlas jusqu'à Ifrane, la « Suisse marocaine », et la forêt de cèdres d'Azrou où vivent les singes en liberté. Pause déjeuner en route, puis descente par Béni Mellal et arrivée à Marrakech le soir.")]))

add(key="merzouga", kind="circuit", img="merzouga", price=470, tiers=[470, 520, 590, 620, 1120, 1620],
    en=dict(slug="dades-gorges-merzouga-desert-tour", title="Dades Gorges & Merzouga Desert Tour",
            dur="3 days / 2 nights",
            short="Over the High Atlas to the Dades and Todra gorges, then a night in a camp in the Erg Chebbi dunes.",
            intro="The classic desert trip from Marrakech, done privately. You cross the High Atlas, follow the road of the thousand kasbahs and end the second day on a camel, heading into the orange dunes of Erg Chebbi for a night under the stars.",
            hl=["Tizi n'Tichka pass (2,260 m)", "Aït Ben Haddou, UNESCO World Heritage", "The hairpin road of the Dades Gorges",
                "Walk in the Todra Gorge", "Camel ride and night in a desert camp in Merzouga"],
            days=[("Marrakech – Aït Ben Haddou – Dades", "Departure at 7:30 over the Tizi n'Tichka pass. Visit of the fortified village of Aït Ben Haddou, then Ouarzazate, the Skoura palm grove and the Valley of Roses. Night in a guesthouse in the Dades Gorges."),
                  ("Dades – Todra – Merzouga", "Morning photo stop on the famous zigzag road, then the Todra Gorge with its 300 m high walls. Via Erfoud to Merzouga, where camels wait at the foot of the dunes. Sunset ride to the camp, dinner and night in the desert."),
                  ("Merzouga – Marrakech", "Wake up early for sunrise over the dunes, camel ride back and breakfast. Long but beautiful drive back through the Draa and Ouarzazate region, arriving in Marrakech in the evening.")]),
    fr=dict(slug="circuit-gorges-dades-merzouga", title="Circuit Gorges du Dadès & désert de Merzouga",
            dur="3 jours / 2 nuits",
            short="Le Haut Atlas, les gorges du Dadès et du Todra, puis une nuit en camp dans les dunes de l'Erg Chebbi.",
            intro="Le grand classique du désert au départ de Marrakech, en privé. Vous traversez le Haut Atlas, suivez la route des mille kasbahs et terminez le deuxième jour à dos de dromadaire, en direction des dunes orangées de l'Erg Chebbi pour une nuit sous les étoiles.",
            hl=["Le col du Tizi n'Tichka (2 260 m)", "Aït Ben Haddou, patrimoine mondial de l'UNESCO", "La route en lacets des gorges du Dadès",
                "Balade dans les gorges du Todra", "Balade à dromadaire et nuit en camp à Merzouga"],
            days=[("Marrakech – Aït Ben Haddou – Dadès", "Départ à 7h30 par le col du Tizi n'Tichka. Visite du ksar d'Aït Ben Haddou, puis Ouarzazate, la palmeraie de Skoura et la vallée des Roses. Nuit en maison d'hôtes dans les gorges du Dadès."),
                  ("Dadès – Todra – Merzouga", "Arrêt photo le matin sur la célèbre route en zigzag, puis les gorges du Todra et leurs parois de 300 m. Par Erfoud jusqu'à Merzouga, où les dromadaires attendent au pied des dunes. Balade au coucher du soleil jusqu'au camp, dîner et nuit dans le désert."),
                  ("Merzouga – Marrakech", "Réveil tôt pour le lever du soleil sur les dunes, retour à dromadaire et petit-déjeuner. Longue mais belle route du retour par la région du Drâa et de Ouarzazate, arrivée à Marrakech le soir.")]))

add(key="imperial", kind="circuit", img="fes", price=670, tiers=[670, 720, 780, 845, 1120, 1800],
    en=dict(slug="imperial-cities-tour", title="Imperial Cities Tour: 5 Cities in 5 Days",
            dur="5 days / 4 nights",
            short="Casablanca, Rabat, Meknes, Volubilis and Fes, finishing with a guided day in Marrakech.",
            intro="Five great cities of Morocco in one smooth private tour. Short drives, central hotels and a final day in Marrakech so you end the trip where it started, with time to enjoy it.",
            hl=["Hassan II Mosque, Casablanca", "Royal Rabat and the Kasbah of the Udayas", "Bab Mansour gate in Meknes",
                "Roman ruins of Volubilis", "A full day in the medina of Fes", "Marrakech: Bahia Palace, souks and Jemaa el-Fnaa"],
            days=[("Marrakech – Casablanca – Rabat", "Pick-up in Marrakech and drive to Casablanca. Visit of the Hassan II Mosque and the Corniche, then on to Rabat. Night in Rabat."),
                  ("Rabat – Meknes – Volubilis – Fes", "Morning in Rabat (Hassan Tower, Kasbah of the Udayas). Drive to Meknes and its monumental Bab Mansour gate, then the Roman city of Volubilis with its mosaics. Evening arrival in Fes."),
                  ("Fes", "A full day in Fes el Bali, the largest car-free medina in the world: the Bou Inania madrasa, the Al Attarine madrasa, the Nejjarine fountain, the craft souks and the tanneries. A local guide can be added on request."),
                  ("Fes – Middle Atlas – Marrakech", "Through Ifrane and the cedar forest of Azrou, where macaques live, then down to the plains of Beni Mellal and on to Marrakech."),
                  ("Marrakech", "A day to discover Marrakech: Koutoubia Mosque, Bahia Palace, the Saadian Tombs, the souks and, at the end of the day, the square of Jemaa el-Fnaa. Drop-off at your riad or the airport.")]),
    fr=dict(slug="circuit-villes-imperiales", title="Circuit des villes impériales : 5 villes en 5 jours",
            dur="5 jours / 4 nuits",
            short="Casablanca, Rabat, Meknès, Volubilis et Fès, avec une dernière journée guidée à Marrakech.",
            intro="Cinq grandes villes du Maroc dans un circuit privé fluide. Des trajets courts, des hôtels bien placés et une dernière journée à Marrakech pour finir le voyage là où il a commencé, en prenant le temps.",
            hl=["La mosquée Hassan II, Casablanca", "Rabat la royale et la kasbah des Oudayas", "La porte Bab Mansour à Meknès",
                "Les ruines romaines de Volubilis", "Une journée entière dans la médina de Fès", "Marrakech : palais de la Bahia, souks et Jemaa el-Fna"],
            days=[("Marrakech – Casablanca – Rabat", "Prise en charge à Marrakech et route vers Casablanca. Visite de la mosquée Hassan II et de la Corniche, puis Rabat. Nuit à Rabat."),
                  ("Rabat – Meknès – Volubilis – Fès", "Matinée à Rabat (tour Hassan, kasbah des Oudayas). Route vers Meknès et sa porte monumentale Bab Mansour, puis la cité romaine de Volubilis et ses mosaïques. Arrivée à Fès le soir."),
                  ("Fès", "Une journée complète à Fès el Bali, la plus grande médina piétonne du monde : la médersa Bou Inania, la médersa Al Attarine, la fontaine Nejjarine, les souks d'artisans et les tanneries. Un guide local peut être ajouté sur demande."),
                  ("Fès – Moyen Atlas – Marrakech", "Par Ifrane et la forêt de cèdres d'Azrou, où vivent les singes magots, puis descente vers les plaines de Béni Mellal et route vers Marrakech."),
                  ("Marrakech", "Une journée pour découvrir Marrakech : la Koutoubia, le palais de la Bahia, les tombeaux saadiens, les souks et, en fin de journée, la place Jemaa el-Fna. Dépôt à votre riad ou à l'aéroport.")]))

add(key="zagora", kind="circuit", img="zagora", price=140, tiers=[140, 150, 180, 195, 370, 570],
    en=dict(slug="ouarzazate-zagora-tour", title="Ouarzazate & Zagora Desert Tour",
            dur="3 days / 2 nights",
            short="Aït Ben Haddou, Ouarzazate and the endless palm groves of the Draa Valley down to Zagora.",
            intro="A relaxed desert trip without very long drives. You follow the Draa Valley, one of the longest palm oases in Morocco, to the gateway of the Sahara at Zagora.",
            hl=["Aït Ben Haddou kasbah", "Ouarzazate and the Taourirt kasbah", "Draa Valley palm groves and old ksour",
                "Optional camel ride at sunset in Zagora", "Tamegroute pottery village and its old Koranic library"],
            days=[("Marrakech – Aït Ben Haddou – Ouarzazate", "Over the Tizi n'Tichka pass to Aït Ben Haddou. Afternoon in Ouarzazate, the 'door of the desert', with the Taourirt kasbah. Night in Ouarzazate."),
                  ("Ouarzazate – Draa Valley – Zagora", "Via Agdz and the Kissane mountains, the road follows the Draa River and its palm groves. Arrival in Zagora in the afternoon; camel ride at sunset possible. Night in Zagora."),
                  ("Zagora – Tamegroute – Marrakech", "Morning visit of Tamegroute, known for its green pottery and old library, then drive back north to Marrakech, arriving in the evening.")]),
    fr=dict(slug="circuit-ouarzazate-zagora", title="Circuit Ouarzazate & désert de Zagora",
            dur="3 jours / 2 nuits",
            short="Aït Ben Haddou, Ouarzazate et les palmeraies sans fin de la vallée du Drâa jusqu'à Zagora.",
            intro="Un voyage au désert tranquille, sans trajets trop longs. Vous suivez la vallée du Drâa, l'une des plus longues oasis du Maroc, jusqu'aux portes du Sahara à Zagora.",
            hl=["La kasbah d'Aït Ben Haddou", "Ouarzazate et la kasbah de Taourirt", "Les palmeraies et les anciens ksour du Drâa",
                "Balade à dromadaire au coucher du soleil à Zagora (en option)", "Tamegroute, son village de potiers et sa bibliothèque coranique"],
            days=[("Marrakech – Aït Ben Haddou – Ouarzazate", "Passage du col du Tizi n'Tichka jusqu'à Aït Ben Haddou. Après-midi à Ouarzazate, la « porte du désert », et la kasbah de Taourirt. Nuit à Ouarzazate."),
                  ("Ouarzazate – vallée du Drâa – Zagora", "Par Agdz et les montagnes du Kissane, la route suit l'oued Drâa et ses palmeraies. Arrivée à Zagora l'après-midi ; balade à dromadaire possible au coucher du soleil. Nuit à Zagora."),
                  ("Zagora – Tamegroute – Marrakech", "Visite le matin de Tamegroute, connue pour sa poterie verte et son ancienne bibliothèque, puis route vers le nord et arrivée à Marrakech le soir.")]))

add(key="ouzoud2", kind="circuit", img="binelouidane", price=140, tiers=[140, 150, 180, 195, 370, 570],
    en=dict(slug="ouzoud-bin-el-ouidane-tour", title="Ouzoud Waterfalls & Bin El Ouidane Lake",
            dur="2 days / 1 night",
            short="The highest waterfalls in Morocco, a night by a turquoise lake and the natural bridge of Imi n'Ifri.",
            intro="A short green escape from Marrakech. See the Ouzoud waterfalls without rushing, sleep by the lake of Bin El Ouidane and come back through the Berber villages around Demnate.",
            hl=["Ouzoud waterfalls (110 m) and the olive-tree path", "Barbary macaques along the river",
                "Sunset over Bin El Ouidane lake", "Boat or kayak on the lake (optional)", "Imi n'Ifri natural bridge near Demnate"],
            days=[("Marrakech – Ouzoud – Bin El Ouidane", "Departure at 8:00 towards the Middle Atlas. Walk down to the foot of the Ouzoud falls, lunch by the water, then drive on to Bin El Ouidane. Night in a lodge by the lake."),
                  ("Bin El Ouidane – Demnate – Marrakech", "Free morning on the lake (boat, kayak or swimming in season). Drive back via Demnate and the natural rock bridge of Imi n'Ifri. Arrival in Marrakech late afternoon.")]),
    fr=dict(slug="circuit-ouzoud-bin-el-ouidane", title="Cascades d'Ouzoud & lac de Bin El Ouidane",
            dur="2 jours / 1 nuit",
            short="Les plus hautes cascades du Maroc, une nuit au bord d'un lac turquoise et le pont naturel d'Imi n'Ifri.",
            intro="Une courte échappée verte depuis Marrakech. Profitez des cascades d'Ouzoud sans vous presser, dormez au bord du lac de Bin El Ouidane et rentrez par les villages berbères autour de Demnate.",
            hl=["Les cascades d'Ouzoud (110 m) et le sentier des oliviers", "Les singes magots le long de l'oued",
                "Coucher de soleil sur le lac de Bin El Ouidane", "Bateau ou kayak sur le lac (en option)", "Le pont naturel d'Imi n'Ifri près de Demnate"],
            days=[("Marrakech – Ouzoud – Bin El Ouidane", "Départ à 8h vers le Moyen Atlas. Descente à pied jusqu'au pied des cascades d'Ouzoud, déjeuner au bord de l'eau, puis route vers Bin El Ouidane. Nuit dans un lodge au bord du lac."),
                  ("Bin El Ouidane – Demnate – Marrakech", "Matinée libre sur le lac (bateau, kayak ou baignade en saison). Retour par Demnate et le pont de roche naturel d'Imi n'Ifri. Arrivée à Marrakech en fin d'après-midi.")]))

add(key="todra2", kind="circuit", img="todra", price=140, tiers=[140, 150, 180, 195, 370, 570],
    en=dict(slug="ouarzazate-todra-gorge-tour", title="Ouarzazate & Todra Gorge Tour",
            dur="2 days / 1 night",
            short="Aït Ben Haddou, the Valley of Roses and the canyon of Todra in a short two-day loop.",
            intro="The best of the south in two days. Ideal if you don't have time for Merzouga but want to see the kasbahs, the oases and one of the most impressive canyons of Morocco.",
            hl=["Tizi n'Tichka pass", "Aït Ben Haddou", "Skoura palm grove and Valley of Roses", "Walk in the Todra Gorge", "Dades Valley on the way back"],
            days=[("Marrakech – Ouarzazate – Tinghir", "Over the High Atlas to Aït Ben Haddou and Ouarzazate, then through Skoura and Kelaat M'Gouna, the Valley of Roses. Night in Tinghir, near the gorge."),
                  ("Todra Gorge – Dades – Marrakech", "Morning walk in the Todra Gorge between its high red walls. Return west through the Dades Valley and Ouarzazate, arriving in Marrakech in the evening.")]),
    fr=dict(slug="circuit-ouarzazate-gorges-todra", title="Circuit Ouarzazate & gorges du Todra",
            dur="2 jours / 1 nuit",
            short="Aït Ben Haddou, la vallée des Roses et le canyon du Todra en une courte boucle de deux jours.",
            intro="Le meilleur du sud en deux jours. Idéal si vous n'avez pas le temps d'aller à Merzouga mais voulez voir les kasbahs, les oasis et l'un des plus beaux canyons du Maroc.",
            hl=["Le col du Tizi n'Tichka", "Aït Ben Haddou", "La palmeraie de Skoura et la vallée des Roses", "Balade dans les gorges du Todra", "La vallée du Dadès au retour"],
            days=[("Marrakech – Ouarzazate – Tinghir", "Traversée du Haut Atlas jusqu'à Aït Ben Haddou et Ouarzazate, puis Skoura et Kelaat M'Gouna, la vallée des Roses. Nuit à Tinghir, près des gorges."),
                  ("Gorges du Todra – Dadès – Marrakech", "Balade le matin dans les gorges du Todra, entre leurs hautes parois rouges. Retour vers l'ouest par la vallée du Dadès et Ouarzazate, arrivée à Marrakech le soir.")]))

# ---------------------------------------------------------------- DAY TRIPS
add(key="agafay", kind="day", img="agafay", price=80,
    en=dict(slug="agafay-desert-trip", title="Agafay Desert Sunset Trip", dur="Half day · afternoon",
            short="The stone desert 40 minutes from Marrakech, with camels or quad and sunset over the Atlas.",
            intro="No time for the Sahara? The Agafay desert is only 40 km from Marrakech. Rolling stone hills, total silence and the snowy Atlas on the horizon. You choose the formula: simple sunset, camel ride, quad, or dinner in a desert camp.",
            hl=["Private transfer from your riad", "Sunset over the Atlas mountains", "Camel ride or quad (optional)", "Dinner and music in a desert camp (optional)"],
            days=[("Afternoon", "Pick-up at about 15:00 and drive south-west to the Agafay plateau. Optional activity: camel ride or quad bike."),
                  ("Sunset & evening", "Enjoy the sunset from the hills. If you chose the dinner formula, evening in a camp with Moroccan dinner. Return to Marrakech around 21:00.")]),
    fr=dict(slug="excursion-desert-agafay", title="Excursion au désert d'Agafay au coucher du soleil", dur="Demi-journée · après-midi",
            short="Le désert de pierres à 40 minutes de Marrakech, à dromadaire ou en quad, coucher de soleil sur l'Atlas.",
            intro="Pas le temps d'aller au Sahara ? Le désert d'Agafay est à seulement 40 km de Marrakech. Des collines de pierre, un silence total et l'Atlas enneigé à l'horizon. Vous choisissez la formule : coucher de soleil simple, dromadaire, quad ou dîner dans un camp.",
            hl=["Transfert privé depuis votre riad", "Coucher de soleil sur l'Atlas", "Balade à dromadaire ou quad (en option)", "Dîner et musique dans un camp (en option)"],
            days=[("Après-midi", "Prise en charge vers 15h et route vers le plateau d'Agafay. Activité en option : dromadaire ou quad."),
                  ("Coucher de soleil & soirée", "Profitez du coucher du soleil depuis les collines. Avec la formule dîner, soirée dans un camp avec repas marocain. Retour à Marrakech vers 21h.")]))

add(key="gardens", kind="day", img="majorelle", price=70,
    en=dict(slug="marrakech-gardens-tour", title="Marrakech Gardens Tour", dur="Half day",
            short="Majorelle Garden, the Menara olive grove and a drive through the Palmeraie.",
            intro="A green, calm side of Marrakech. Ideal for a morning before lunch or for travellers who want to see the city without walking all day.",
            hl=["Majorelle Garden and its famous blue", "Menara Gardens and basin with the Atlas behind", "Drive through the Palmeraie", "Flexible start time"],
            days=[("Morning or afternoon", "Pick-up at your riad. Visit of the Majorelle Garden (ticket not included), then the Menara Gardens and its 12th-century basin, and a drive through the palm grove of the Palmeraie. About 4 hours.")]),
    fr=dict(slug="excursion-jardins-marrakech", title="Excursion des jardins de Marrakech", dur="Demi-journée",
            short="Le jardin Majorelle, l'oliveraie de la Ménara et un tour dans la Palmeraie.",
            intro="Le côté vert et calme de Marrakech. Parfait pour une matinée avant le déjeuner, ou pour découvrir la ville sans marcher toute la journée.",
            hl=["Le jardin Majorelle et son bleu célèbre", "Les jardins de la Ménara et leur bassin face à l'Atlas", "Tour dans la Palmeraie", "Heure de départ flexible"],
            days=[("Matin ou après-midi", "Prise en charge à votre riad. Visite du jardin Majorelle (billet non inclus), puis les jardins de la Ménara et leur bassin du XIIe siècle, et un tour dans la Palmeraie. Environ 4 heures.")]))

add(key="medina", kind="day", img="koutoubia", price=85,
    en=dict(slug="marrakech-medina-day-tour", title="Marrakech Medina Day Tour", dur="Full day",
            short="Koutoubia, Bahia Palace, Saadian Tombs, the souks and Jemaa el-Fnaa.",
            intro="All the must-sees of the old city in one day, with a driver to take you between the different areas and save your legs.",
            hl=["Koutoubia Mosque", "Bahia Palace and Saadian Tombs", "Ben Youssef Madrasa", "The souks of the medina", "Jemaa el-Fnaa at sunset"],
            days=[("Morning", "Koutoubia Mosque and its gardens, then the Kasbah district with the Saadian Tombs and the Bahia Palace."),
                  ("Afternoon", "Ben Youssef Madrasa and the souks, lunch break in the medina, and Jemaa el-Fnaa at the end of the day. Local official guide on request.")]),
    fr=dict(slug="excursion-medina-marrakech", title="Visite de la médina de Marrakech", dur="Journée complète",
            short="La Koutoubia, le palais de la Bahia, les tombeaux saadiens, les souks et Jemaa el-Fna.",
            intro="Tous les incontournables de la vieille ville en une journée, avec un chauffeur pour vous déplacer entre les quartiers et ménager vos jambes.",
            hl=["La mosquée Koutoubia", "Le palais de la Bahia et les tombeaux saadiens", "La médersa Ben Youssef", "Les souks de la médina", "Jemaa el-Fna au coucher du soleil"],
            days=[("Matin", "La Koutoubia et ses jardins, puis le quartier de la Kasbah avec les tombeaux saadiens et le palais de la Bahia."),
                  ("Après-midi", "La médersa Ben Youssef et les souks, pause déjeuner dans la médina, et Jemaa el-Fna en fin de journée. Guide officiel local sur demande.")]))

add(key="ourika", kind="day", img="ourika", price=90,
    en=dict(slug="ourika-valley-day-trip", title="Ourika Valley & Setti Fatma Waterfalls", dur="Full day · 8:30",
            short="Berber villages, an argan cooperative and a walk to the waterfalls of Setti Fatma.",
            intro="The closest Atlas valley to Marrakech, green all year round. A great first contact with the mountains and Berber life.",
            hl=["Argan oil women's cooperative", "Visit of a traditional Berber house", "Walk to the Setti Fatma waterfalls", "Lunch by the river"],
            days=[("Morning", "Departure at 8:30. Stops at an argan cooperative and in a Berber house for mint tea, with views over the valley."),
                  ("Midday & afternoon", "In Setti Fatma, walk up to the first waterfalls with a local mountain guide, lunch on a terrace by the river, return to Marrakech around 17:00.")]),
    fr=dict(slug="excursion-vallee-ourika", title="Vallée de l'Ourika & cascades de Setti Fatma", dur="Journée · départ 8h30",
            short="Villages berbères, coopérative d'argan et balade jusqu'aux cascades de Setti Fatma.",
            intro="La vallée de l'Atlas la plus proche de Marrakech, verte toute l'année. Un premier contact idéal avec la montagne et la vie berbère.",
            hl=["Coopérative féminine d'huile d'argan", "Visite d'une maison berbère traditionnelle", "Balade jusqu'aux cascades de Setti Fatma", "Déjeuner au bord de la rivière"],
            days=[("Matin", "Départ à 8h30. Arrêts dans une coopérative d'argan et dans une maison berbère pour un thé à la menthe, avec vue sur la vallée."),
                  ("Midi & après-midi", "À Setti Fatma, montée à pied jusqu'aux premières cascades avec un guide de montagne local, déjeuner en terrasse au bord de l'oued, retour à Marrakech vers 17h.")]))

add(key="imlil", kind="day", img="imlil", price=110,
    en=dict(slug="imlil-asni-day-trip", title="Tahanaout, Asni & Imlil: Toubkal Valley Day Trip", dur="Full day",
            short="Mountain villages, the Moulay Brahim gorge and a walk at the foot of Toubkal.",
            intro="Drive into the heart of the High Atlas, at the foot of Jbel Toubkal, the highest peak in North Africa. Fresh air, walnut trees and terraced villages.",
            hl=["Tahanaout village", "Moulay Brahim gorge", "Asni market (Saturday)", "Walk from Imlil to Aroumd village", "Views of Toubkal (4,167 m)"],
            days=[("Morning", "Through Tahanaout and the Moulay Brahim gorge to Asni, then up to Imlil (1,740 m)."),
                  ("Afternoon", "Easy walk with a local guide to the village of Aroumd, lunch in a guesthouse with mountain views, return to Marrakech in the late afternoon.")]),
    fr=dict(slug="excursion-imlil-asni", title="Tahanaout, Asni & Imlil : vallée du Toubkal", dur="Journée complète",
            short="Villages de montagne, gorges de Moulay Brahim et balade au pied du Toubkal.",
            intro="Une journée au cœur du Haut Atlas, au pied du Jbel Toubkal, le plus haut sommet d'Afrique du Nord. Air pur, noyers et villages en terrasses.",
            hl=["Le village de Tahanaout", "Les gorges de Moulay Brahim", "Le souk d'Asni (le samedi)", "Balade d'Imlil au village d'Aroumd", "Vue sur le Toubkal (4 167 m)"],
            days=[("Matin", "Par Tahanaout et les gorges de Moulay Brahim jusqu'à Asni, puis montée jusqu'à Imlil (1 740 m)."),
                  ("Après-midi", "Balade facile avec un guide local jusqu'au village d'Aroumd, déjeuner dans une maison d'hôtes face aux montagnes, retour à Marrakech en fin d'après-midi.")]))

add(key="oukaimeden", kind="day", img="oukaimeden", price=130,
    en=dict(slug="oukaimeden-day-trip", title="Oukaimeden High Atlas Day Trip", dur="Full day",
            short="The high plateau at 2,600 m: snow in winter, shepherds and rock carvings in summer.",
            intro="Oukaimeden is the highest ski resort in Africa and a beautiful mountain plateau the rest of the year. A great day out when Marrakech is too hot or when the Atlas is white.",
            hl=["Road through the Ourika valley", "Plateau at 2,600 m", "Skiing or sledging in winter", "Prehistoric rock carvings", "Lunch with a view"],
            days=[("Full day", "Departure in the morning via the Ourika valley and the mountain road up to Oukaimeden. Free time on the plateau: snow activities in winter, walk to the rock carvings and shepherd huts in summer. Return to Marrakech in the afternoon.")]),
    fr=dict(slug="excursion-oukaimeden", title="Excursion à Oukaïmeden, Haut Atlas", dur="Journée complète",
            short="Le haut plateau à 2 600 m : neige en hiver, bergers et gravures rupestres en été.",
            intro="Oukaïmeden est la plus haute station de ski d'Afrique et un très beau plateau de montagne le reste de l'année. Une belle sortie quand il fait trop chaud à Marrakech ou quand l'Atlas est blanc.",
            hl=["Route par la vallée de l'Ourika", "Plateau à 2 600 m", "Ski ou luge en hiver", "Gravures rupestres préhistoriques", "Déjeuner avec vue"],
            days=[("Journée", "Départ le matin par la vallée de l'Ourika et la route de montagne jusqu'à Oukaïmeden. Temps libre sur le plateau : neige en hiver, balade vers les gravures rupestres et les bergeries en été. Retour à Marrakech l'après-midi.")]))

add(key="rabat", kind="day", img="rabat", price=140,
    en=dict(slug="rabat-day-trip", title="Rabat Day Trip from Marrakech", dur="Full day",
            short="The capital: Hassan Tower, Mausoleum of Mohammed V, Kasbah of the Udayas and the medina.",
            intro="A calm, elegant capital by the ocean, about 3.5 hours from Marrakech by motorway. Perfect if you want to see another side of Morocco.",
            hl=["Hassan Tower and Mausoleum of Mohammed V", "Kasbah of the Udayas and Andalusian garden", "Rabat medina", "Ocean views over the Bou Regreg"],
            days=[("Full day", "Early departure by motorway. Visit of the Hassan Tower and the Mausoleum, walk through the blue and white Kasbah of the Udayas and its garden, lunch and free time in the medina, then drive back to Marrakech in the evening.")]),
    fr=dict(slug="excursion-rabat", title="Excursion à Rabat depuis Marrakech", dur="Journée complète",
            short="La capitale : tour Hassan, mausolée Mohammed V, kasbah des Oudayas et médina.",
            intro="Une capitale calme et élégante au bord de l'océan, à environ 3h30 de Marrakech par l'autoroute. Parfait pour découvrir une autre facette du Maroc.",
            hl=["La tour Hassan et le mausolée Mohammed V", "La kasbah des Oudayas et le jardin andalou", "La médina de Rabat", "Vue sur l'océan et le Bouregreg"],
            days=[("Journée", "Départ tôt par l'autoroute. Visite de la tour Hassan et du mausolée, balade dans la kasbah bleue et blanche des Oudayas et son jardin, déjeuner et temps libre dans la médina, puis retour à Marrakech le soir.")]))

add(key="casablanca", kind="day", img="casablanca", price=155,
    en=dict(slug="casablanca-day-trip", title="Casablanca Day Trip from Marrakech", dur="Full day · 7:00",
            short="Hassan II Mosque on the ocean, the Corniche, the Habous quarter and Mohammed V Square.",
            intro="Morocco's big modern city in one day. The highlight is the Hassan II Mosque, built over the Atlantic, one of the few mosques in Morocco open to non-Muslim visitors.",
            hl=["Hassan II Mosque (inside visit possible)", "Ain Diab Corniche", "Habous quarter (new medina)", "Mohammed V Square", "Lunch with ocean view"],
            days=[("Full day", "Departure at 7:00. Visit of the Hassan II Mosque (guided visit ticket not included), drive along the Corniche, lunch by the ocean, then the Habous quarter and Mohammed V Square. Return to Marrakech in the evening.")]),
    fr=dict(slug="excursion-casablanca", title="Excursion à Casablanca depuis Marrakech", dur="Journée · départ 7h",
            short="La mosquée Hassan II sur l'océan, la Corniche, le quartier des Habous et la place Mohammed V.",
            intro="La grande ville moderne du Maroc en une journée. Le moment fort : la mosquée Hassan II, construite sur l'Atlantique, l'une des rares mosquées du pays ouvertes aux non-musulmans.",
            hl=["La mosquée Hassan II (visite intérieure possible)", "La Corniche d'Aïn Diab", "Le quartier des Habous", "La place Mohammed V", "Déjeuner face à l'océan"],
            days=[("Journée", "Départ à 7h. Visite de la mosquée Hassan II (billet de visite guidée non inclus), route le long de la Corniche, déjeuner au bord de l'océan, puis le quartier des Habous et la place Mohammed V. Retour à Marrakech le soir.")]))

add(key="ouarzazate", kind="day", img="aitbenhaddou", price=155,
    en=dict(slug="ouarzazate-ait-ben-haddou-day-trip", title="Ouarzazate & Aït Ben Haddou Day Trip", dur="Full day · about 13 h",
            short="Tizi n'Tichka pass, the kasbah of Aït Ben Haddou and the film studios of Ouarzazate.",
            intro="A long but unforgettable day over the High Atlas to the gates of the desert. Many famous films were shot here.",
            hl=["Tizi n'Tichka pass (2,260 m)", "Aït Ben Haddou, UNESCO World Heritage", "Atlas film studios", "Taourirt kasbah", "Berber villages along the road"],
            days=[("Full day", "Departure at 7:00 over the Tizi n'Tichka pass with photo stops. Visit of Aït Ben Haddou, lunch, then Ouarzazate: the film studios and the Taourirt kasbah (entrance tickets not included). Return to Marrakech around 20:00.")]),
    fr=dict(slug="excursion-ouarzazate-ait-ben-haddou", title="Excursion Ouarzazate & Aït Ben Haddou", dur="Journée · environ 13 h",
            short="Le col du Tizi n'Tichka, la kasbah d'Aït Ben Haddou et les studios de cinéma de Ouarzazate.",
            intro="Une longue journée inoubliable à travers le Haut Atlas jusqu'aux portes du désert. De nombreux films célèbres ont été tournés ici.",
            hl=["Le col du Tizi n'Tichka (2 260 m)", "Aït Ben Haddou, patrimoine de l'UNESCO", "Les studios de cinéma Atlas", "La kasbah de Taourirt", "Villages berbères en chemin"],
            days=[("Journée", "Départ à 7h par le col du Tizi n'Tichka avec arrêts photo. Visite d'Aït Ben Haddou, déjeuner, puis Ouarzazate : les studios de cinéma et la kasbah de Taourirt (entrées non incluses). Retour à Marrakech vers 20h.")]))

add(key="3valleys", kind="day", img="dades", price=170,
    en=dict(slug="three-valleys-atlas-day-trip", title="Three Valleys of the Atlas Day Trip", dur="Full day",
            short="Ourika, Imlil and Ouirgane in one big loop, finishing at Lalla Takerkoust lake.",
            intro="A full loop through three different Atlas valleys, for travellers who want to see a lot of mountain landscapes in one day.",
            hl=["Ourika Valley", "Asni and Imlil at the foot of Toubkal", "Ouirgane valley and its red earth", "Lalla Takerkoust lake at the end of the day"],
            days=[("Full day", "Pick-up in the morning. Ourika valley and a tea stop in a Berber house, then across to Asni and up to Imlil. After lunch, down the Ouirgane valley and back to Marrakech via the lake of Lalla Takerkoust.")]),
    fr=dict(slug="excursion-trois-vallees", title="Excursion des trois vallées de l'Atlas", dur="Journée complète",
            short="L'Ourika, Imlil et Ouirgane en une grande boucle, avec le lac Lalla Takerkoust pour finir.",
            intro="Une boucle complète à travers trois vallées différentes de l'Atlas, pour ceux qui veulent voir un maximum de paysages de montagne en une journée.",
            hl=["La vallée de l'Ourika", "Asni et Imlil au pied du Toubkal", "La vallée d'Ouirgane et sa terre rouge", "Le lac Lalla Takerkoust en fin de journée"],
            days=[("Journée", "Prise en charge le matin. Vallée de l'Ourika et thé dans une maison berbère, puis traversée vers Asni et montée à Imlil. Après le déjeuner, descente par la vallée d'Ouirgane et retour à Marrakech par le lac Lalla Takerkoust.")]))
