U = 'https://epictravelmorocco.com/wp-content/uploads/2025/11/'
TOURS_E = [
 dict(id=3339, url='majestic-kasbah-and-desert-adventure', name='Majestic Kasbah & Desert Adventure', days=5, start='Marrakech', end='Marrakech',
  img=U+'pexels-henrik-le-botos-1588507-3878114-scaled.jpg', kind='Desert',
  intro='A 5-day immersive journey through Morocco’s kasbahs, valleys, gorges, and desert dunes.',
  plan=[
  ('Marrakech | Ouarzazate | Roses Valley | Dades Gorges', 'Pick up from your Hotel/Riad at 8:30 AM. Climb the Tizi n’Tichka pass (2260m). Visit Ouarzazate “Hollywood of Africa”, Studio Cinema, and Kasbah Taourirt. Stop for lunch, then drive the “Road of the Thousand Kasbahs”. Visit Kalaat Mgouna (“Rose’s Kastel”). Continue to Dades Gorge hotel for dinner and overnight stay.'),
  ('Dades Gorges | Todra Gorges | Merzouga', 'After breakfast, drive to Tinghir and Toudgha Gorges. Stop for lunch, then continue to Erfoud. Visit a fossil workshop. Experience a 1-hour camel ride through Erg Chebbi dunes at sunset. Dinner and overnight in a comfortable desert camp.'),
  ('Deep cultural and nomad lifestyle experience', 'Early sunrise hike on dunes, then camel trek back. Visit Berber villages, desert plateau, Khamliya musicians, and Rissani town for Souk visit. Lunch in a family house. Return to Erg Chebbi for free evening with stunning dune views. Dinner and overnight in hotel.'),
  ('Merzouga | Rissani | Alnif | Agdez | Ouarzazate', 'Early sunrise hike, breakfast, then depart to Rissani. Visit Souk, then continue through Draa Valley with adobe Kasbahs and Berber villages. Drive up to Ouarzazate admiring Draa Valley geological formations and Ait Saoun col.'),
  ('Ouarzazate | Ait Benhaddou | Marrakech', 'Breakfast at hotel, then drive to Ait Benhaddou Kasbah (UNESCO World Heritage Site). 1-hour walking tour, then lunch in Atlas Mountains. Continue to Marrakech via Tizi N’Tichka. Drop off at hotel. End of Majestic Kasbah and Desert Adventure tour.'),
 ]),
 dict(id=3338, url='discover-northern-morocco-tour', name='Discover Northern Morocco', days=6, start='Casablanca', end='Casablanca',
  img=U+'pexels-abdel-achkouk-2861018-22717119-scaled.jpg', kind='North & imperial cities',
  intro='Explore Morocco’s imperial cities, stunning landscapes, and cultural highlights across 6 unforgettable days.',
  plan=[
  ('Pick up from Casablanca airport', 'Pick up from Casablanca Airport. Start your day with a guide visiting the famous Hassan II Mosque, the largest religious building in the world open for non-Muslims during Fridays. Explore the Souk in the old medina, Bab Marrakech gate, charming hotels, United Nations square, the corniche in Ain Diab, and Morocco Mall.'),
  ('Casablanca | Rabat | Tangier', 'After breakfast, depart to Rabat. Explore the city with a local guide visiting Almohad northern walls of the Oudaya Kasbah, Hassan Tower, and the King’s Palace. Then drive straight to Tangier, the gateway between Europe and Africa.'),
  ('Visit of Tangier | Chefchaouen', 'Explore Tangier’s Medina, Socco market, and American museum. Visit Cap Spartel for ocean views where Atlantic meets Mediterranean, then the Caves of Hercules. Drive to Chefchaouen through Rif mountains. Overnight in Chefchaouen.'),
  ('Explore Chefchaouen | Fes', 'Guided tour of Chefchaouen: Utta Hammam Square, Kasbah & Museum, Ras El-Ma Spring. Then drive to Fes with lunch stop on the way if desired. Overnight in Fes.'),
  ('Explore the city of Fes', 'Visit Marinid Tombs, Musee des Armes, Bab Boujeloud (Blue Gate), Fez El-Bali, Rue Talaa Kebira, Karaouiyine Mosque, Zaouia Moulay Idriss II, Chrabliyine Mosque, souks, Fondouk El Najjarine, Musee Dar El-Batha, Bab Ftouh, Fez El Jedid, Medersa Bou Inania, University of Al-Qarawiyyin, Medersa el Attarin. Overnight in Fes.'),
  ('Fes | Volubilis | Casablanca', 'After breakfast, drive 2 hours outside Fes to explore the Roman ruins of Volubilis. Discover mosaics, columns, the basilica, triumphal arch, and Roman city structures. Then drive straight back to Casablanca. End of the tour.'),
 ]),
 dict(id=3331, url='n', name='Authentic Morocco Tour', days=11, start='Casablanca', end='Casablanca',
  img=U+'pexels-gabriel-garcia-1263144-2404046-scaled.jpg', kind='Grand tour',
  intro='Experience the magic of Morocco through imperial cities, Atlas Mountains, and Sahara dunes. From Casablanca to Marrakech, every day unveils a new story.',
  note='Customized tour options available upon request.',
  plan=[
  ('Casablanca', 'The excitement of your personalized tour begins when you first start planning your trip, even before you land in the Casablanca airport. Your English-speaking driver will meet you at the airport. If time permits, visit Hassan II Mosque, one of the largest mosques in the world. Guided tour available, with views of the Atlantic Ocean through glass flooring sections.'),
  ('Rabat | Fes', 'Drive to Fes with a stop in Rabat. Explore the capital, Oudaïa Kasbah, Bab Oudaïa gate, Musée de Oudaïa, Andalusian garden, then continue to Fes. Enjoy Moroccan breakfast and lunch along the way.'),
  ('Explore Fes', 'Spend the day exploring Fes medina. Visit tanneries, King’s Palace, pottery markets, and taste local dishes. Guided tour explains cultural and historical details.'),
  ('Volubilis | Meknes | Fes', 'Visit Roman ruins of Volubilis, then the holy town of Moulay Idris. Afternoon tour to Meknes, UNESCO World Heritage site. Return to Fes for dinner and overnight.'),
  ('Fes | Merzouga', 'Travel across Middle Atlas Mountains through forests, rock faces, and Berber villages, descending into the Sahara Desert. Overnight at riad/hotel in Merzouga.'),
  ('Explore Sahara style life', 'Afternoon four-wheel drive across Sahara dunes. Optional camel ride to Berber tents for overnight stay. Experience desert life and sunset views.'),
  ('Toudgha Gorges | Boumalen Dades', 'Sunrise on dunes, breakfast in the open desert, then camel ride back. Travel by 4×4 to Toudgha Gorges and explore towering rock walls. Overnight in Boumalen Dades.'),
  ('Dades | Ait Benhaddou | Marrakech', 'Drive to Marrakech via Ouarzazate. Visit Kasbah Ait Benhaddou, High Atlas Mountains, and arrive in Marrakech. Explore city highlights and enjoy local culture.'),
  ('Explore the Red City of Marrakech', 'Guided tour of Marrakech: Bahia Palace, Saadian tombs, and city streets. Experience the lively Jemaa El Fna square and traditional Moroccan cuisine.'),
  ('Transfer to Casablanca', 'Return to Casablanca. Free time for shopping and sightseeing. Last opportunity to buy souvenirs and enjoy Moroccan flavors.'),
  ('Departure to the airport', 'Arrive at the airport 2-3 hours before departure. End of your 11-day Authentic Morocco Tour with Epic Travel Morocco.'),
 ]),
]
