# Morocco Sky Travel – program content (moroccoskytravel.com)
# Same facts as the original pages, rewritten for clarity. One dict per WordPress page ID.
U = 'https://moroccoskytravel.com/wp-content/uploads/'

TOURS = [
# ---------------------------------------------------------------- multi-day
dict(id=2789, url='2day-trip-to-the-desert-mahamid', kind='multi', days=2, start='Marrakech', end='Marrakech',
  title='2-Day Desert Trip from Marrakech to Mhamid & Erg Lihoudi',
  card='2-Day Marrakech Desert Trip to Mhamid',
  lead='The Draa Valley, a camel ride into the dunes and a night under the Saharan stars, all in a compact two-day escape from Marrakech.',
  img=U+'2025/11/pexels-taryn-elliott-4253829-1-scaled.jpg', alt='Camel caravan crossing the dunes near Mhamid, Morocco',
  hl=['Palm groves and kasbahs of Agdez','Pottery and the old Quranic library of Tamgrout','Sunset camel ride at Erg Lihoudi','Night in a desert camp with a Berber dinner','Ait Benhaddou, a UNESCO World Heritage site'],
  it=[('Marrakech – Agdez – Tamgrout – Erg Lihoudi','We leave Marrakech early in the morning and cross the High Atlas to Agdez, with its palm groves and kasbahs. We continue to Tamgrout to see its pottery workshops and Quranic library, then reach Mhamid at the edge of the Sahara. A camel ride takes you to Erg Lihoudi for sunset, followed by a traditional Berber dinner and a night in a desert camp.'),
      ('Erg Lihoudi – Zagora – Ouarzazate – Ait Benhaddou – Marrakech','After breakfast, ride the camels back to Mhamid. We drive through Zagora, the gateway to the desert, to Ouarzazate, with time for the Kasbah Taourirt or the Atlas Film Studios if the schedule allows. A stop at the UNESCO-listed kasbah of Ait Benhaddou comes next, then we cross the Tizi n\'Tichka pass back to Marrakech, where the tour ends.')],
  outro='A short, efficient way to experience Morocco\'s desert landscapes and iconic sites, combining adventure, culture and beautiful scenic drives.',
  desc='2-day private desert trip from Marrakech to Mhamid: Agdez, Tamgrout, a sunset camel ride at Erg Lihoudi, a desert camp night and Ait Benhaddou.',
  kw='2 day desert trip from Marrakech'),

dict(id=2771, url='2-days-trip-from-fes', kind='multi', days=2, start='Fes', end='Fes',
  title='2-Day Desert Tour from Fes to Merzouga',
  card='2-Day Fes to Merzouga Desert Tour',
  lead='The Middle Atlas, cedar forests and the golden dunes of Erg Chebbi: a compact two-day desert adventure from Fes.',
  img=U+'2025/11/pexels-mographe-30283798-scaled.jpg', alt='Erg Chebbi sand dunes in Merzouga, Morocco',
  hl=['Ifrane, the "Little Switzerland" of Morocco','Azrou cedar forest and Barbary macaques','Sunset camel trek on the Erg Chebbi dunes','Berber dinner, music and a night in luxury desert tents'],
  it=[('Fes – Ifrane – Azrou – Midelt – Merzouga','We leave Fes early in the morning and stop in Ifrane, known as "Little Switzerland" for its alpine-style houses. In Azrou we walk in the cedar forest and meet the Barbary macaques. Lunch is in Midelt, then we continue via Errachidia to Merzouga. After checking in at the desert camp, a camel trek takes you into the Erg Chebbi dunes for sunset. Traditional Berber dinner, music and overnight in luxury tents.'),
      ('Merzouga – Errachidia – Midelt – Ifrane – Fes','After breakfast, ride the camels back to Merzouga and begin the return journey. We drive via Errachidia and Midelt, with a lunch or rest stop, and an optional break in Azrou. Passing through Ifrane once more, we arrive in Fes in the late afternoon or evening.')],
  outro='A compact yet unforgettable trip that combines Atlas landscapes, a night in the Sahara and authentic Moroccan culture.',
  desc='Private 2-day desert tour from Fes to Merzouga: Ifrane, Azrou cedar forest, a sunset camel trek on Erg Chebbi and a night in a luxury desert camp.',
  kw='2 day desert tour from Fes'),

dict(id=2779, url='3days-trip-from-agadir-to-the-desert', kind='multi', days=3, start='Agadir', end='Agadir',
  title='3-Day Desert Tour from Agadir to Erg Chagaga',
  card='3-Day Agadir to Erg Chagaga Tour',
  lead='The Anti-Atlas mountains, the Draa Valley and Morocco\'s largest dunes on a three-day adventure from Agadir.',
  img=U+'2025/11/pexels-thomas-balabaud-735585-34855142-scaled.jpg', alt='Sunset over the Erg Chagaga dunes, Morocco',
  hl=['Taroudant, the walled "Little Marrakech"','Berber rug workshops in Taznakht','Camel trek and sunset on the Erg Chagaga dunes','Pottery of Tamgrout and the palm groves of Agdez'],
  it=[('Agadir – Taroudant – Taznakht – Foum Zguid – Erg Chagaga','Early departure from Agadir. A coffee stop in Taroudant, known as "Little Marrakech", then on to Taznakht to visit Berber rug workshops and traditional crafts. We rest in the small desert town of Foum Zguid before heading into the Sahara. At Erg Chagaga, a camel trek takes you into the dunes for sunset, followed by a Berber dinner, music and a night in a luxury desert camp.'),
      ('Erg Chagaga – Mhamid – Tamgrout – Agdez','After breakfast, ride camels back to the vehicles and drive to Mhamid for a short visit. We continue to Tamgrout to see its pottery workshops and Quranic library, then reach Agdez to explore its kasbahs and palm groves. Overnight in Agdez.'),
      ('Agdez – Agadir','A scenic drive back through the Draa Valley and the Anti-Atlas mountains. We arrive in Agadir in the afternoon or early evening, with time for the beach or the souks if you wish.')],
  outro='Three days of desert adventure, culture and dramatic scenery across southern Morocco.',
  desc='3-day private desert tour from Agadir: Taroudant, Taznakht rugs, camel trek and luxury camp at Erg Chagaga, Tamgrout and Agdez.',
  kw='3 day desert tour from Agadir'),

dict(id=2794, url='3-day-itinerary-marrakech-to-imlil-and-agafay-desert', kind='multi', days=3, start='Marrakech', end='Marrakech',
  title='3-Day Tour from Marrakech to Imlil & the Agafay Desert',
  card='3-Day Marrakech to Imlil & Agafay',
  lead='Berber villages in the High Atlas, then quad biking, camels and sunset in the Agafay desert, all within easy reach of Marrakech.',
  img=U+'2025/11/pexels-luigi-maggio-1750047758-28076410-scaled.jpg', alt='Imlil valley and the High Atlas mountains near Marrakech',
  hl=['Imlil and the Berber villages of the High Atlas','Short trek to Aremd village','Quad biking and a camel ride in the Agafay desert','Sunset and a night in an Agafay desert camp'],
  it=[('Marrakech – Imlil','We leave Marrakech at about 8:00 and drive 70 km to Imlil via Asni. Explore the village and take a short trek to Aremd for wonderful views, with lunch at a local guesthouse or café. Check in to your mountain accommodation (such as Kasbah du Toubkal or Auberge Imlil), then relax or explore nearby Berber villages. Dinner and overnight in Imlil.'),
      ('Imlil – Agafay Desert','Departure at about 8:00 for the Agafay desert. Lunch at the desert camp, then an afternoon of quad biking (1 to 1.5 hours) and a camel ride across the stony desert. Watch the sunset over the hills, then enjoy dinner and a night in a desert camp such as Agafay Desert Luxury Camp or Scarabeo Camp.'),
      ('Agafay Desert – Marrakech','Breakfast at the camp and departure at about 9:00 for the 40 km drive back to Marrakech, arriving between 10:00 and 11:00. The rest of the day is free: markets, gardens or a traditional hammam, and lunch in the city before your departure.')],
  outro='Mountain scenery, village life and desert fun combined in one relaxed three-day trip.',
  desc='3-day private tour from Marrakech: Imlil and Berber villages in the High Atlas, then quad biking, a camel ride and a camp night in the Agafay desert.',
  kw='Marrakech to Imlil and Agafay desert'),

dict(id=2800, url='4-day-itinerary-marrakech-to-agdez-and-back', kind='multi', days=4, start='Marrakech', end='Marrakech',
  title='4-Day Tour from Marrakech to Taroudant, Erg Chagaga & Agdez',
  card='4-Day Marrakech, Erg Chagaga & Agdez',
  lead='Mountain passes, saffron fields, a camel ride into Erg Chagaga and the palm groves of Agdez on a four-day loop from Marrakech.',
  img=U+'2025/11/caption-5.jpg', alt='Desert camp at Erg Chagaga in southern Morocco',
  hl=['The Tizi n\'Test pass and the walled city of Taroudant','Saffron fields of Taliouine','Camel ride and stargazing at Erg Chagaga','Ait Benhaddou and the Tizi n\'Tichka pass'],
  it=[('Marrakech – Tizi n\'Test – Taroudant','Departure at about 8:00 for a 200 km drive over the Tizi n\'Test pass, with superb mountain views. Lunch at a local restaurant, then explore Taroudant\'s historic medina, ramparts and souks. Dinner and overnight in Taroudant (Riad Maryam or Hotel Palais Salam).'),
      ('Taroudant – Taliouine – Foum Zguid – Erg Chagaga','Departure at about 8:00 for a 300 km drive via Taliouine, where we stop to see the saffron fields, then Taznakht and Foum Zguid. We reach Erg Chagaga around 15:00 to 16:00 and ride camels to the desert camp. Dinner, stargazing and overnight at the camp.'),
      ('Erg Chagaga – Mhamid – Tamgrout – Agdez','Departure at about 8:00 for a 250 km drive via Mhamid, with a short stop, and Tamgrout. Lunch in Tamgrout or Agdez, then explore Agdez and its palm groves. Dinner and overnight at Kasbah Agdez or a local guesthouse.'),
      ('Agdez – Ouarzazate – Ait Benhaddou – Marrakech','Departure at about 8:00. A stop in Ouarzazate, then a visit to the UNESCO-listed Ait Benhaddou. After lunch on the way, we pass Telouet and cross the Tizi n\'Tichka pass back to Marrakech, arriving between 18:00 and 19:00.')],
  outro='A varied four-day journey of mountain roads, southern towns and the open desert.',
  desc='4-day private tour from Marrakech: Tizi n\'Test, Taroudant, Taliouine saffron, a camel ride and camp at Erg Chagaga, Agdez and Ait Benhaddou.',
  kw='4 day tour from Marrakech to Erg Chagaga'),

dict(id=2805, url='4day-trip-to-the-desert', kind='multi', days=4, start='Marrakech', end='Marrakech',
  title='4-Day Desert Tour from Marrakech to Merzouga & Agdez',
  card='4-Day Marrakech to Merzouga Desert Tour',
  lead='The High Atlas, the Rose Valley, the dunes of Erg Chebbi and the Draa Valley on a classic four-day desert circuit.',
  img=U+'2025/11/garganta-dades-1.jpg', alt='Winding road through the Dades Gorge, Morocco',
  hl=['Ait Benhaddou kasbah, a UNESCO World Heritage site','Skoura oasis and Kasbah Amridil','Rose Valley and the Todra Gorge','Sunset camel trek on Erg Chebbi and a night in a luxury camp','Kasbah des Caids and the Draa Valley palm groves'],
  it=[('Marrakech – Tizi n\'Tichka – Ait Benhaddou – Ouarzazate – Skoura','Early departure across the High Atlas via the Tizi n\'Tichka pass. Visit the kasbah of Ait Benhaddou, a UNESCO World Heritage site, then stop in Ouarzazate for the Taourirt Kasbah or the Atlas Film Studios. In Skoura, visit Kasbah Amridil and enjoy the oasis. Overnight in Skoura.'),
      ('Skoura – Rose Valley – Todra Gorge – Merzouga','Drive through the Rose Valley and Kelaat M\'Gouna, then walk in the Todra Gorge. Continue to Erfoud, famous for its fossils, and on to Merzouga. A camel trek takes you into the Erg Chebbi dunes at sunset. Berber dinner, stargazing and overnight in a luxury desert camp.'),
      ('Merzouga – Alnif – Nkob – Agdez','After breakfast, ride the camels back to Merzouga. We drive via Alnif to Nkob for lunch, then continue to Agdez to explore the old Kasbah des Caids and the Draa Valley palm groves. Overnight in Agdez.'),
      ('Agdez – Ouarzazate – Marrakech','A short stop in Ouarzazate, then back over the Tizi n\'Tichka pass to Marrakech. Drop-off at your hotel or the airport.')],
  outro='A classic desert circuit combining scenic mountain drives, cultural highlights and a night in the Sahara.',
  desc='4-day private desert tour from Marrakech: Ait Benhaddou, Skoura, the Rose Valley, Todra Gorge, a camel trek and luxury camp in Merzouga, and Agdez.',
  kw='4 day desert tour from Marrakech to Merzouga'),

dict(id=2809, url='5-day-trip-from-fes-chagaga-desert-marrakech', kind='multi', days=5, start='Fes', end='Marrakech',
  title='5-Day Tour from Fes to Erg Chagaga & Marrakech',
  card='5-Day Fes to Erg Chagaga & Marrakech',
  lead='Cross Morocco from Fes to Marrakech via the Middle Atlas, the Todra Gorge, the Erg Chagaga dunes and Ait Benhaddou.',
  img=U+'2025/11/ait-ben-haddou.jpg', alt='The kasbah of Ait Benhaddou, Morocco',
  hl=['Ifrane, Azrou cedar forest and Barbary macaques','The red cliffs of the Todra Gorge','Sunset camel trek and camp at Erg Chagaga','Picnic with a nomadic family','UNESCO-listed Ait Benhaddou'],
  it=[('Fes – Ifrane – Azrou – Tinghir','Early departure from Fes. A photo stop in Ifrane, the "Little Switzerland", then the cedar forest of Azrou and its Barbary macaques. We continue through the Middle Atlas to Tinghir. Overnight in Tinghir.'),
      ('Tinghir – Todra Gorge – Nkob – Agdez','Explore the Todra Gorge and its towering red cliffs, then drive through the Saghro mountains. Lunch in Nkob and a visit to its old kasbahs. Arrival in Agdez and a walk in the Draa Valley palm groves. Overnight in Agdez.'),
      ('Agdez – Zagora – Tamgrout – Mhamid – Erg Chagaga','Drive to Zagora and visit Tamgrout, known for its green pottery and old Quranic library. Continue to Mhamid, the gateway to the desert, for a picnic lunch with a nomadic family. A sunset camel trek leads you to the Erg Chagaga dunes. Berber music, dinner and overnight in a desert camp.'),
      ('Erg Chagaga – Foum Zguid – Taznakht – Ait Benhaddou','Cross the desert to Foum Zguid and Taznakht, known for their local crafts. Arrive in Ait Benhaddou and visit its UNESCO-listed kasbah. Overnight in Ait Benhaddou.'),
      ('Ait Benhaddou – Tizi n\'Tichka – Marrakech','Drive through the High Atlas via the Tizi n\'Tichka pass to Marrakech. Drop-off at your hotel or the airport.')],
  outro='Mountains, desert and history in one immersive five-day crossing of Morocco.',
  desc='5-day private tour from Fes to Marrakech: Ifrane, Todra Gorge, Agdez, a camel trek and camp at Erg Chagaga, and Ait Benhaddou.',
  kw='5 day tour from Fes to Marrakech'),

dict(id=2816, url='6-day-trip-from-fes', kind='multi', days=6, start='Fes', end='Fes',
  title='6-Day Tour from Fes: Ouzoud Waterfalls, Marrakech & Merzouga',
  card='6-Day Fes, Ouzoud, Marrakech & Merzouga',
  lead='Waterfalls, the Red City and the Sahara dunes on a six-day loop from Fes through the Middle and High Atlas.',
  img=U+'2025/11/Cascades-dOuzoud-1.jpg', alt='The Ouzoud waterfalls in Morocco',
  hl=['The Ouzoud waterfalls (hike or boat ride)','A full day exploring Marrakech','Telouet and Ait Benhaddou kasbahs','Sunset camel trek on Erg Chebbi and a night in a luxury camp'],
  it=[('Fes – Ifrane – Azrou – Khenifra – Ouzoud Waterfalls','Drive through the Middle Atlas via Ifrane, Azrou and Khenifra. Explore the spectacular Ouzoud waterfalls on foot or by boat. Dinner and overnight near the falls.'),
      ('Ouzoud Waterfalls – Marrakech','A morning at the waterfalls, then the drive to Marrakech. Check in, visit Jemaa el-Fnaa square and enjoy Moroccan cuisine. Overnight in Marrakech.'),
      ('Marrakech','A full day in Marrakech: the Koutoubia Mosque, the Saadian Tombs, Majorelle Garden, the Bahia Palace and the souks of the medina. Lunch at a local restaurant. Overnight in Marrakech.'),
      ('Marrakech – Tizi n\'Tichka – Ait Benhaddou – Skoura','Cross the Tizi n\'Tichka pass and visit Telouet and Ait Benhaddou. Optional visits in Ouarzazate, then on to Skoura for dinner and overnight.'),
      ('Skoura – Rose Valley – Todra Gorge – Merzouga','Drive through the Rose Valley, the Todra Gorge and Erfoud to Merzouga. Sunset camel trek in the Erg Chebbi dunes, dinner and overnight in a luxury desert camp.'),
      ('Merzouga – Midelt – Ifrane – Fes','Drive back to Fes with optional stops in Errachidia, Midelt, Azrou and Ifrane. Farewell dinner in Fes and overnight, or transfer to the airport.')],
  outro='Natural wonders, historic cities and the desert combined in one complete six-day journey.',
  desc='6-day private tour from Fes: Ouzoud waterfalls, a full day in Marrakech, Ait Benhaddou, the Todra Gorge and a camel trek with a luxury camp in Merzouga.',
  kw='6 day tour from Fes'),

dict(id=2821, url='6-days-trip-from-marrakech-echagaga-essouira', kind='multi', days=6, start='Marrakech', end='Marrakech',
  title='6-Day Tour from Marrakech: Erg Chagaga Desert & Essaouira',
  card='6-Day Marrakech, Erg Chagaga & Essaouira',
  lead='The High Atlas, the Sahara dunes of Erg Chagaga and the Atlantic charm of Essaouira in six days.',
  img=U+'2025/11/pexels-tom-d-arby-3904203-6662921-scaled.jpg', alt='Essaouira harbour and ramparts on the Atlantic coast',
  hl=['Telouet, Ait Benhaddou and Ouarzazate','Picnic with a nomadic family and a sunset camel trek','Lake Iriki on the Dakar Rally route','Two nights in coastal Essaouira'],
  it=[('Marrakech – Tizi n\'Tichka – Ait Benhaddou – Agdez','Cross the Tizi n\'Tichka pass, visit the Telouet kasbah, Ait Benhaddou and Ouarzazate. Arrive in Agdez for dinner and a night among palm groves and kasbahs.'),
      ('Agdez – Tamgrout – Erg Chagaga','Drive down the Draa Valley and stop in Tamgrout for its pottery and Quranic library. Picnic with a nomadic family, then a sunset camel trek to Erg Chagaga. Berber music, dinner and overnight in a luxury desert camp.'),
      ('Erg Chagaga – Lake Iriki – Foum Zguid – Taroudant','Cross the dry Lake Iriki on the Dakar Rally route, then pass Foum Zguid and Taznakht, known for its Berber rugs. Overnight in Taroudant, the walled "Little Marrakech".'),
      ('Taroudant – Agadir – Essaouira','Drive via Agadir and along the Atlantic coast to Essaouira, with stops for the beach and lunch. A relaxed evening and overnight in Essaouira.'),
      ('Essaouira','A full day in Essaouira: the medina, the Skala de la Ville ramparts, the port and the beach. Optional water sports. Overnight in Essaouira.'),
      ('Essaouira – Marrakech','A scenic drive back to Marrakech with a visit to an argan oil cooperative. Drop-off at your hotel or the airport.')],
  outro='Mountains, desert adventure and coastal charm in one rich six-day journey.',
  desc='6-day private tour from Marrakech: Ait Benhaddou, the Draa Valley, a camel trek and luxury camp at Erg Chagaga, Taroudant and two nights in Essaouira.',
  kw='6 day tour from Marrakech to the desert and Essaouira'),

dict(id=2847, url='camel-trekking-adventure', kind='multi', days=7, start='Marrakech', end='Erg Chagaga',
  title='7-Day Camel Trek from Mhamid to Erg Chagaga',
  card='7-Day Camel Trekking Adventure',
  lead='A week on foot and by camel across the Sahara with nomad guides, camping under the stars all the way to the great dunes of Erg Chagaga.',
  img=U+'2025/11/pexels-zakariahanif-12214734-2-scaled.jpg', alt='Camel trekking in the Sahara desert near Erg Chagaga',
  hl=['Six nights camping in the desert','About 6 to 7 hours of trekking a day, with a camel to ride when you are tired','Meals cooked at camp by your nomad team','Final camp at the Erg Chagaga dunes'],
  it=[('Marrakech – Mhamid: start of the trek','Departure from Marrakech at about 8:00 by minibus or 4x4 (about 300 km) across the Atlas Mountains to Mhamid. Lunch in Mhamid or on the way. Meet your camel guides, go over the trekking plan and set off on the trek to the first camp. Traditional Moroccan dinner and overnight in desert tents.'),
      ('Trekking from Mhamid','About 4 hours of camel trekking in the morning, a picnic lunch, then 2 to 3 hours of trekking in the afternoon to the next camp. Set up camp, dinner and overnight in desert tents.'),
      ('Trekking towards Erg Chagaga','Each day follows the same rhythm: about 4 hours of trekking in the morning, a picnic lunch, then 2 to 3 hours in the afternoon to a new camping spot. Evenings are for setting up camp, dinner and enjoying the peace of the desert. Overnight in desert tents.'),
      ('Arrival at Erg Chagaga','A final morning trek to the Erg Chagaga dunes and a picnic lunch. The afternoon is free to explore the dunes, relax or take an optional camel ride. Farewell dinner and a last night in the desert camp.')],
  daynums=['Day 1','Day 2','Days 3–6','Day 7'],
  outro='An immersive week of desert landscapes, nomadic culture and camp life, with traditional meals under the stars.',
  desc='7-day camel trek in the Moroccan Sahara from Mhamid to Erg Chagaga: 6 to 7 hours a day on foot or by camel, nomad guides and nights in desert camps.',
  kw='camel trekking Morocco'),

dict(id=2814, url='8-days-tour-from-casablnca', kind='multi', days=8, start='Casablanca', end='Marrakech',
  title='8-Day Morocco Tour from Casablanca',
  card='8-Day Morocco Tour from Casablanca',
  lead='The imperial cities, the blue city of Chefchaouen, the Sahara and Marrakech in eight well-paced days.',
  img=U+'2025/11/istockphoto-647288678-612x612-1.jpg', alt='The blue streets of Chefchaouen, Morocco',
  hl=['Hassan II Mosque in Casablanca','Rabat and blue Chefchaouen','Volubilis, Meknes and a full day in Fes','Sunset camel trek and a camp night in Merzouga','Dades Gorge, Ait Benhaddou and Marrakech'],
  it=[('Arrival in Casablanca','Visit the Hassan II Mosque, the Royal Palace (outside), the Corniche and the Habous quarter. Lunch at Rick\'s Café and dinner on the Corniche. Overnight in Casablanca.'),
      ('Casablanca – Rabat – Chefchaouen','In Rabat, visit the Kasbah of the Udayas, the Hassan Tower and the Mausoleum of Mohammed V, then continue to Chefchaouen. Explore its blue streets, the Kasbah Museum and the Ras El Maa spring. Overnight in Chefchaouen.'),
      ('Chefchaouen – Volubilis – Meknes – Fes','Stop at the Roman ruins of Volubilis and in Meknes (Bab Mansour and the Mausoleum of Moulay Ismail) on the way to Fes. Dinner at a local restaurant and overnight in Fes.'),
      ('Fes','Explore the Fes medina, the Bou Inania Madrasa, Al-Qarawiyyin University, the Chouara tannery, the Royal Palace (outside) and the Mellah. Lunch in the medina and dinner at a local restaurant. Overnight in Fes.'),
      ('Fes – Ifrane – Midelt – Merzouga','Drive via Ifrane and the Azrou cedar forests, with lunch in Midelt, then through Errachidia and Erfoud to Merzouga. Sunset camel trek on Erg Chebbi, dinner and overnight in a desert camp.'),
      ('Merzouga – Todra Gorge – Dades Gorge','Visit the Todra Gorge, have lunch, then continue to the Dades Gorge. Dinner and overnight in the Dades Gorge.'),
      ('Dades Gorge – Ait Benhaddou – Marrakech','Drive through the Rose Valley, Skoura, Ouarzazate, Ait Benhaddou and Telouet to Marrakech for dinner and overnight.'),
      ('Marrakech','A full-day tour: Jemaa el-Fnaa, the Koutoubia Mosque, the Saadian Tombs, Majorelle Garden, the Bahia Palace and the souks. Lunch at a local restaurant. End of the tour, with an airport transfer if needed.')],
  outro='A complete introduction to Morocco, from historic cities and mountains to the Sahara desert.',
  desc='8-day private Morocco tour from Casablanca: Rabat, Chefchaouen, Fes, a camel trek and camp in Merzouga, the Dades Gorge, Ait Benhaddou and Marrakech.',
  kw='8 day Morocco tour from Casablanca'),

dict(id=2784, url='1o-days-trip-from-fes', kind='multi', days=10, start='Fes', end='Fes',
  title='10-Day Morocco Tour from Fes',
  card='10-Day Morocco Tour from Fes',
  lead='Imperial cities, the Rif and the Atlas, Marrakech and two nights in the Sahara on a complete ten-day loop from Fes.',
  img=U+'2025/11/pexels-earth-photart-2149767641-33998377-scaled.jpg', alt='The medina of Fes, Morocco',
  hl=['Two full days in Fes','Meknes, Volubilis and blue Chefchaouen','Rabat and two nights in Marrakech','Two nights in the Merzouga desert, with 4x4 and sandboarding','Gnawa music in Khamlia village'],
  it=[('Arrival in Fes','Pick-up from the airport or train station. Explore Fes el Bali, Bab Bou Jeloud, Al Quaraouiyine University, the tanneries and the Bou Inania Madrasa. Overnight in Fes.'),
      ('Fes','Visit the Royal Palace (Dar el Makhzen), the Jewish quarter (Mellah), the Nejjarine Museum and the lively souks. Overnight in Fes.'),
      ('Fes – Meknes – Volubilis – Chefchaouen','Drive to Chefchaouen with stops in Meknes (Bab Mansour, the Mausoleum of Moulay Ismail, Heri es-Souani) and at the Roman ruins of Volubilis. Overnight in Chefchaouen.'),
      ('Chefchaouen – Rabat','Explore the Chefchaouen medina and the Ras El Maa waterfall, then drive to Rabat to visit the Hassan Tower, the Mausoleum of Mohammed V, the Kasbah of the Udayas and the Chellah. Overnight in Rabat.'),
      ('Rabat – Marrakech','Drive to Marrakech and explore Jemaa el-Fnaa square and the Koutoubia Mosque. Overnight in Marrakech.'),
      ('Marrakech','Visit the Bahia Palace, Majorelle Garden, the Saadian Tombs, the souks and the Ben Youssef Madrasa. Overnight in Marrakech.'),
      ('Marrakech – Tizi n\'Tichka – Ouarzazate','Cross the High Atlas via the Tizi n\'Tichka pass and visit the Atlas Film Studios and the Kasbah Taourirt. Overnight in Ouarzazate.'),
      ('Ouarzazate – Rose Valley – Todra Gorge – Merzouga','Stops in the Rose Valley and the Todra Gorge, then on to Merzouga for a camel trek, a traditional Berber dinner and a night in a luxury desert camp.'),
      ('Merzouga','A full day in the desert: the dunes, sandboarding, a 4x4 tour and a visit to Khamlia village for Gnawa music. Overnight in Merzouga.'),
      ('Merzouga – Erfoud – Midelt – Fes','Drive back to Fes via Erfoud and Midelt. End of the tour on arrival in Fes.')],
  outro='Imperial cities, mountains, the desert and Morocco\'s great monuments in one comprehensive journey.',
  desc='10-day private Morocco tour from Fes: Chefchaouen, Rabat, Marrakech, Ouarzazate, the Todra Gorge and two nights in the Merzouga desert.',
  kw='10 day Morocco tour from Fes'),

dict(id=2839, url='10-days-trip-from-casablana', kind='multi', days=10, start='Casablanca', end='Casablanca',
  title='10-Day Morocco Tour from Casablanca',
  card='10-Day Morocco Tour from Casablanca',
  lead='Casablanca, Chefchaouen, Fes, the Sahara and Marrakech: Morocco\'s highlights in ten days, ending at Casablanca airport.',
  img=U+'2025/11/from-marrakech-merzouga-3-day-desert-safari-with-food-5153405.webp', alt='Camel ride on the Merzouga dunes at sunset',
  hl=['Hassan II Mosque and Rabat','A full day in blue Chefchaouen','Volubilis, Meknes and a full day in Fes','Camel trek and desert camp in Merzouga','Rose Valley, Ait Benhaddou and a full day in Marrakech'],
  it=[('Arrival in Casablanca','Airport pick-up. Visit the Hassan II Mosque, the Corniche and the Habous quarter, with a meal at Rick\'s Café. Overnight in Casablanca.'),
      ('Casablanca – Rabat – Chefchaouen','In Rabat, visit the Hassan Tower, the Mausoleum of Mohammed V, the Kasbah of the Udayas and the Chellah. Continue to Chefchaouen for the night.'),
      ('Chefchaouen','Explore the medina and the Ras El Maa waterfall, and walk up to the Spanish Mosque for panoramic views. Overnight in Chefchaouen.'),
      ('Chefchaouen – Volubilis – Meknes – Fes','Visit the Roman ruins of Volubilis and the highlights of Meknes: Bab Mansour, Heri es-Souani and the Mausoleum of Moulay Ismail. Overnight in Fes.'),
      ('Fes','Explore Fes el Bali, Al Quaraouiyine University, the Bou Inania Madrasa, the tanneries and the souks. Overnight in Fes.'),
      ('Fes – Ifrane – Azrou – Merzouga','Stops in Ifrane and Azrou, then on to Merzouga for a sunset camel trek through Erg Chebbi. Overnight in a desert camp with a Berber dinner and music.'),
      ('Merzouga – Todra Gorge – Rose Valley','Visit the Todra Gorge, then continue to the Rose Valley, famous for its roses and landscapes. Overnight in the Rose Valley.'),
      ('Rose Valley – Skoura – Ouarzazate – Ait Benhaddou – Marrakech','Visit Kasbah Amridil in Skoura, the Atlas Film Studios and Kasbah Taourirt in Ouarzazate, and the UNESCO site of Ait Benhaddou. Cross the Tizi n\'Tichka pass to Marrakech. Overnight in Marrakech.'),
      ('Marrakech','Visit Jemaa el-Fnaa, the Koutoubia Mosque, the Bahia Palace, Majorelle Garden, the Saadian Tombs and the souks. Overnight in Marrakech.'),
      ('Marrakech – Casablanca Airport','Drive to Casablanca (about 3 hours) and transfer to the airport for your departure.')],
  outro='A complete Moroccan adventure through cities, mountains and desert, combining culture, history and natural beauty.',
  desc='10-day private Morocco tour from Casablanca: Rabat, Chefchaouen, Fes, a camel trek in Merzouga, the Rose Valley, Ait Benhaddou and Marrakech.',
  kw='10 day Morocco tour from Casablanca'),

dict(id=2834, url='11-days-trip', kind='multi', days=11, start='Tangier', end='Marrakech',
  title='11-Day Morocco Tour from Tangier to Marrakech',
  card='11-Day Morocco Tour from Tangier',
  lead='From Tangier along the Atlantic coast to Essaouira, then into the Atlas Mountains and on to Marrakech in eleven days.',
  img=U+'2025/11/fb.jpg', alt='Morocco landscape on the 11-day tour from Tangier',
  hl=['Tangier, Rabat and Casablanca','Two nights in Essaouira','Taroudant\'s ramparts and medina','Two nights in Imlil with a full-day Atlas trek','Two days in Marrakech'],
  it=[('Arrival in Tangier','Pick-up from the airport or ferry terminal. Visit the Kasbah Museum, the American Legation Museum, the Caves of Hercules and the medina. Overnight in Tangier.'),
      ('Tangier – Rabat','Drive to Rabat to visit the Hassan Tower, the Kasbah of the Udayas, the Royal Palace (outside) and the Chellah. Overnight in Rabat.'),
      ('Rabat – Casablanca','Drive to Casablanca to visit the Hassan II Mosque, the Corniche, the Habous quarter and Rick\'s Café. Overnight in Casablanca.'),
      ('Casablanca – Essaouira','Drive to Essaouira and explore the medina, the Skala de la Ville and the port, then relax on the beach. Overnight in Essaouira.'),
      ('Essaouira','Explore the Mellah (Jewish quarter) and the artisan workshops, enjoy the beach and fresh seafood. Overnight in Essaouira.'),
      ('Essaouira – Agadir – Taroudant','Drive via Agadir, stopping at the beach and the Oufella ruins. Explore Taroudant\'s ramparts, medina and Assarag square. Overnight in Taroudant.'),
      ('Taroudant – Imlil','Drive to Imlil and relax in the mountain village with views of Mount Toubkal. Overnight in Imlil.'),
      ('Imlil: full-day trek','A full-day trek in the Atlas Mountains to Aremd village or in Toubkal National Park, through Berber villages with stunning views. Overnight in Imlil.'),
      ('Imlil – Marrakech','Drive to Marrakech and visit Jemaa el-Fnaa, the Koutoubia Mosque, the Bahia Palace and the souks. Overnight in Marrakech.'),
      ('Marrakech','Visit Majorelle Garden and the Yves Saint Laurent Museum, the Saadian Tombs, El Badi Palace, the Ben Youssef Madrasa and Le Jardin Secret. Overnight in Marrakech.'),
      ('Departure from Marrakech','Transfer to Marrakech Menara airport for your departure.')],
  outro='City life, coastal beauty and mountain trekking in one diverse and memorable journey.',
  desc='11-day private Morocco tour from Tangier: Rabat, Casablanca, Essaouira, Taroudant, an Atlas trek from Imlil and two days in Marrakech.',
  kw='11 day Morocco tour'),

dict(id=2829, url='15-day-relax-trip-around-morocco', kind='multi', days=15, start='Marrakech', end='Marrakech',
  title='15-Day Relaxed Grand Tour of Morocco',
  card='15-Day Relaxed Morocco Grand Tour',
  lead='Morocco at an unhurried pace: the Atlantic coast, the north, Fes, two nights in the Sahara and four days in Marrakech.',
  img=U+'2025/11/88303797-62559338.jpg', alt='Relaxed Morocco tour through cities, coast and desert',
  hl=['Casablanca, Rabat, Asilah and Tangier','Blue Chefchaouen and two days in Fes','Two nights in the Merzouga desert','Todra Gorge, Ouarzazate and Ait Benhaddou','Four relaxed days in Marrakech, with Ourika Valley'],
  it=[('Marrakech – Casablanca','Visit the Hassan II Mosque, the Royal Palace, the Corniche and the Habous quarter. Lunch at a local restaurant. Overnight in Casablanca.'),
      ('Casablanca – Rabat','Explore the Kasbah of the Udayas, the Hassan Tower, the Mausoleum of Mohammed V, the medina and the Chellah. Lunch in Rabat. Overnight in Rabat.'),
      ('Rabat – Asilah','Discover Asilah\'s whitewashed medina, its murals, the Raissouni Palace and the ramparts. Fresh seafood for lunch. Overnight in Asilah.'),
      ('Asilah – Tangier','Explore the Kasbah Museum, the Grand Socco, the American Legation Museum and Café Hafa. Lunch in Tangier. Overnight in Tangier.'),
      ('Tangier – Chefchaouen','Discover Chefchaouen\'s blue streets, the Kasbah Museum and the Ras El Maa spring. Lunch at a local restaurant. Overnight in Chefchaouen.'),
      ('Chefchaouen – Fes','Visit the Fes medina, the Bou Inania Madrasa, Al-Qarawiyyin University, the souks and the tanneries. Lunch in the medina. Overnight in Fes.'),
      ('Fes','More of Fes: the Royal Palace, Bab Boujloud, the Mellah, the medina or a cooking class. Lunch at a local restaurant. Overnight in Fes.'),
      ('Fes – Ifrane – Midelt – Merzouga','Drive via Ifrane and Azrou, lunch in Midelt, then on through Errachidia and Erfoud. Sunset camel trek to Erg Chebbi and overnight in a desert camp.'),
      ('Merzouga','Sunrise camel ride, lunch at the camp, then a visit to nearby nomad villages or sandboarding. Overnight in the desert camp.'),
      ('Merzouga – Rissani – Todra Gorge – Ouarzazate','Visit the Rissani market and the Todra Gorge on the way. Lunch at a local restaurant, then explore Ouarzazate and the Kasbah Taourirt. Overnight in Ouarzazate.'),
      ('Ouarzazate – Ait Benhaddou – Marrakech','Stop at the UNESCO site of Ait Benhaddou, lunch on the way, then continue to Marrakech. Overnight in Marrakech.'),
      ('Marrakech','Visit Jemaa el-Fnaa, the Koutoubia Mosque, the Saadian Tombs, Majorelle Garden, the Bahia Palace and the souks. Overnight in Marrakech.'),
      ('Marrakech: Ourika Valley or city','A day trip to the Ourika Valley or more of Marrakech, with lunch at a restaurant or riad and time for a hammam. Overnight in Marrakech.'),
      ('Marrakech: free day','A free day for shopping, exploring or simply relaxing. Overnight in Marrakech.'),
      ('Departure from Marrakech','Transfer to the airport according to your flight time, with time for last-minute shopping.')],
  outro='Medinas, coastal towns, the Sahara and the Atlas, explored slowly and in comfort.',
  desc='15-day relaxed private tour of Morocco: Casablanca, Rabat, Asilah, Tangier, Chefchaouen, Fes, two nights in Merzouga and four days in Marrakech.',
  kw='15 day Morocco tour'),

# ---------------------------------------------------------------- day trips
dict(id=2943, url='day-trip-itinerary-marrakech-to-imlil-valley', kind='day', hours='About 9 hours', start='Marrakech', end='Marrakech',
  title='Imlil Valley Day Trip from Marrakech',
  card='Marrakech to Imlil Valley',
  lead='Berber villages, mountain trails and views of Mount Toubkal in the heart of the High Atlas, just 70 km from Marrakech.',
  img=U+'2025/11/imlil-view.jpg.webp', alt='Imlil valley and Berber villages in the High Atlas',
  hl=['Scenic drive into the High Atlas','Imlil, a traditional Berber village','1 to 2 hour hike to Aremd village','Views of Mount Toubkal'],
  steps=[('08:00','Departure from Marrakech','Pick-up from your hotel or riad and a scenic 70 km drive into the Atlas Mountains. Arrival in Imlil at about 10:00.'),
         ('10:00','Imlil village','Walk through the traditional Berber village. A local guide can be arranged to tell you about its culture and traditions.'),
         ('Midday','Hike to Aremd','A 1 to 2 hour hike to Aremd village with wonderful valley and mountain views. Lunch as a picnic or at a local guesthouse serving Berber dishes.'),
         ('Afternoon','Ait Souka and free time','Optional visit to nearby Ait Souka village, then time to relax in Imlil and enjoy the view of Mount Toubkal.'),
         ('15:00','Return to Marrakech','Departure from Imlil at about 15:00, arriving in Marrakech at about 17:00.')],
  inc=['Private transport in an air-conditioned vehicle','Driver','Hotel or riad pick-up and drop-off in Marrakech'], exc=['Lunch and drinks','Local guide (optional)'],
  desc='Private day trip from Marrakech to the Imlil valley: Berber villages, a hike to Aremd and views of Mount Toubkal in the High Atlas.',
  kw='Imlil day trip from Marrakech'),

dict(id=2934, url='day-trip-itinerary-marrakech-to-essaouira', kind='day', hours='About 11 hours', start='Marrakech', end='Marrakech',
  title='Essaouira Day Trip from Marrakech',
  card='Marrakech to Essaouira',
  lead='The UNESCO-listed medina, the sea ramparts, the fishing harbour and the long sandy beach of Morocco\'s favourite coastal town.',
  img=U+'2025/11/pexels-tom-d-arby-3904203-6662921-scaled.jpg', alt='Essaouira ramparts and harbour',
  hl=['UNESCO-listed medina','Skala de la Ville ramparts','Fishing harbour and grilled sardines','Free time on the beach'],
  steps=[('08:00','Departure from Marrakech','Pick-up from your hotel or riad and a 175 km drive west through the countryside. Arrival in Essaouira at about 11:00.'),
         ('11:00','The medina','Wander through the UNESCO-listed medina and its 18th-century architecture, and browse the souks for crafts and textiles. For lunch, try La Table by Madada or Le Patio.'),
         ('Afternoon','Ramparts, harbour and beach','Walk the Skala de la Ville ramparts above the Atlantic, visit the fishing harbour to taste grilled sardines, and relax on the wide sandy beach.'),
         ('16:00','Return to Marrakech','Departure from Essaouira at about 16:00, arriving in Marrakech at about 19:00.')],
  inc=['Private transport in an air-conditioned vehicle','Driver','Hotel or riad pick-up and drop-off in Marrakech'], exc=['Lunch and drinks','Local guide (optional)'],
  desc='Private day trip from Marrakech to Essaouira: the UNESCO medina, the Skala de la Ville ramparts, the fishing harbour and the beach.',
  kw='Essaouira day trip from Marrakech'),

dict(id=2926, url='marrakech-to-cascades-douzoud', kind='day', hours='10 to 11 hours', start='Marrakech', end='Marrakech',
  title='Ouzoud Waterfalls Day Trip from Marrakech',
  card='Marrakech to Ouzoud Waterfalls',
  lead='One of the tallest and most spectacular waterfalls in North Africa, reached through olive groves and Berber villages.',
  img=U+'2025/11/29_6399d4eb0e352s_0.jpg', alt='The Ouzoud waterfalls near Marrakech',
  hl=['The Ouzoud waterfalls from several viewpoints','Barbary macaques living freely','Lunch with a view of the falls','Optional boat ride at the foot of the falls'],
  steps=[('08:00','Departure from Marrakech','Pick-up from your hotel or riad and a drive through the countryside and Atlas foothills, with short stops for photos and refreshments.'),
         ('Late morning','Ouzoud waterfalls','Meet your local guide (optional) and walk down the shaded paths to panoramic viewpoints, often with Barbary macaques nearby.'),
         ('Lunch','By the water (optional)','Choose from local restaurants serving tagines, brochettes and salads, with views of the falls.'),
         ('Afternoon','Free time','A boat ride near the base of the falls, a swim in the natural pools (seasonal) or the top viewpoint for photos.'),
         ('16:30','Return to Marrakech','Departure from Ouzoud at about 16:30, arriving in Marrakech at about 19:00.')],
  inc=['Private transport in an air-conditioned vehicle','Driver','Hotel or riad pick-up and drop-off in Marrakech'], exc=['Lunch and drinks','Local guide (optional)','Boat ride (optional)'],
  desc='Private day trip from Marrakech to the Ouzoud waterfalls: viewpoints, Barbary macaques, lunch by the falls and an optional boat ride.',
  kw='Ouzoud waterfalls day trip from Marrakech'),

dict(id=2947, url='marrakech-to-agafay-desert', kind='day', hours='About 10 hours', start='Marrakech', end='Marrakech',
  title='Agafay Desert Day Trip from Marrakech',
  card='Marrakech to Agafay Desert',
  lead='Quad biking, a camel ride and a desert sunset, just 40 km from Marrakech.',
  img=U+'2025/11/men-in-traditional-attire-riding-camels-across-a-d-2025-04-04-22-20-23-utc-scaled.jpg', alt='Camel ride in the Agafay desert near Marrakech',
  hl=['Quad biking across the Agafay desert','One-hour camel ride','Moroccan lunch at a desert camp','Sunset over the desert'],
  steps=[('09:00','Departure from Marrakech','Pick-up from your hotel or riad and a 40 km drive to the Agafay desert, arriving at about 10:00.'),
         ('Morning','Quad biking','A 1 to 1.5 hour quad bike ride across the desert, with a reputable local operator.'),
         ('12:30','Lunch','Traditional Moroccan lunch at a desert camp or a local restaurant such as Chez Momo.'),
         ('Afternoon','Camel ride','A one-hour camel ride through the desert landscape.'),
         ('Sunset','Desert sunset','Watch the sun go down over the Agafay hills, a perfect moment for photos.'),
         ('Evening','Return to Marrakech','Departure after sunset, arriving in Marrakech at about 19:30.')],
  inc=['Private transport in an air-conditioned vehicle','Driver','Hotel or riad pick-up and drop-off in Marrakech'], exc=['Lunch and drinks','Quad and camel rides (optional)'],
  desc='Private day trip from Marrakech to the Agafay desert: quad biking, a camel ride, lunch at a desert camp and sunset over the desert.',
  kw='Agafay desert day trip from Marrakech'),

dict(id=2952, url='day-trip-itinerary-marrakech-to-ourika-valley', kind='day', hours='About 9.5 hours', start='Marrakech', end='Marrakech',
  title='Ourika Valley Day Trip from Marrakech',
  card='Marrakech to Ourika Valley',
  lead='The Setti Fatma waterfalls, riverside lunches and Berber culture in a green valley of the High Atlas.',
  img=U+'2025/11/ourika.jpg', alt='The Ourika valley in the High Atlas',
  hl=['Hike to the Setti Fatma waterfalls','Lunch by the Ourika river','Local markets and crafts','Berber home or artisan visit (optional)'],
  steps=[('08:00','Departure from Marrakech','Pick-up from your hotel or riad and a 70 km drive to the Ourika Valley, arriving at about 9:30.'),
         ('Mid-morning','Setti Fatma waterfalls','A 1 to 1.5 hour return hike to the Setti Fatma waterfalls, with an optional local guide.'),
         ('Lunch','By the river','Lunch at a local restaurant such as Chez Latifa or Auberge Chez Said, overlooking the river and mountains.'),
         ('Afternoon','Markets and culture','Stroll through local markets, meet artisans or visit a traditional Berber home, and relax by the river.'),
         ('16:00','Return to Marrakech','Departure at about 16:00, arriving in Marrakech at about 17:30.')],
  inc=['Private transport in an air-conditioned vehicle','Driver','Hotel or riad pick-up and drop-off in Marrakech'], exc=['Lunch and drinks','Local guide (optional)'],
  desc='Private day trip from Marrakech to the Ourika Valley: a hike to the Setti Fatma waterfalls, lunch by the river and local Berber culture.',
  kw='Ourika Valley day trip from Marrakech'),

dict(id=2960, url='ouarzazat', kind='day', hours='About 13 hours', start='Marrakech', end='Marrakech',
  title='Ouarzazate & Ait Benhaddou Day Trip from Marrakech',
  card='Marrakech to Ouarzazate & Ait Benhaddou',
  lead='Cross the High Atlas to the gateway of the desert: kasbahs, film studios and the UNESCO-listed ksar of Ait Benhaddou.',
  img=U+'2025/11/ait-ben-haddou.jpg', alt='The ksar of Ait Benhaddou near Ouarzazate',
  hl=['The Tizi n\'Tichka pass','Taourirt Kasbah','Atlas Film Studios','UNESCO-listed Ait Benhaddou','Fint Oasis (optional)'],
  steps=[('07:00','Departure from Marrakech','Pick-up from your hotel or riad and a 200 km drive over the Tizi n\'Tichka pass. Arrival in Ouarzazate at about 11:00.'),
         ('11:00','Taourirt Kasbah','About an hour exploring this historic 19th-century kasbah.'),
         ('Midday','Atlas Film Studios','A 1 to 1.5 hour guided tour of one of the largest film studios in the world.'),
         ('Lunch','In Ouarzazate','Lunch at a local restaurant, such as Le Relais de Marrakech.'),
         ('Afternoon','Ait Benhaddou','A 30-minute drive to the UNESCO site, then 1.5 to 2 hours exploring the ksar and its panoramic views. Optional visit to the Fint Oasis and its Berber villages.'),
         ('16:00','Return to Marrakech','Departure at about 16:00, arriving in Marrakech at about 20:00.')],
  inc=['Private transport in an air-conditioned vehicle','Driver','Hotel or riad pick-up and drop-off in Marrakech'], exc=['Lunch and drinks (optional)'],
  desc='Private day trip from Marrakech to Ouarzazate: the Tizi n\'Tichka pass, Taourirt Kasbah, the Atlas Film Studios and the UNESCO site of Ait Benhaddou.',
  kw='Ouarzazate day trip from Marrakech'),
]
